### PR TITLE
removed brainos_core patchelf, it is probably unnecessary

### PR DESCRIPTION
**Pull request by trifonov-bc**

### CODE REVIEW

**Comment by trifonov-bc** [comment]
@codymgriffin it seems that patchelf is unnecessary, this way it works for bstem in brainos_vision

**Comment by codymgriffin** [comment]
Does fixrpath do anything on OS X?

**Comment by trifonov-bc** [comment]
@codymgriffin yes it works both on linux and OSX, but as you see now it is removed.

**Comment by codymgriffin** [comment]
those path fixes may be necessary on OS X, but let's move forward with removing this.  Ideally, CMAKE would take care of any platform-specific installation (like messing with the RPATH).

**Comment by trifonov-bc** [comment]
@codymgriffin cmake takes care of RPATH, but this hack is to enable caching. I.e. cmake installs library into robustus cache, but then we copy it from cache to each venv if necessary. If you link to shared libraries, then RPATHS need to be fixed as well. In some cases it is necessary, in some not - i.e. RPATH pointing to robustus cache dir and libraries can be found there.

**Pull request merged**
